### PR TITLE
Two straightforward new features

### PR DESCRIPTION
**Pull request by gameboo**

### CODE REVIEW

**Comment by mn416** [comment]
Looks good.  The `testPlusArgs` instance for `Module` is a bit unexpected since simulator arguments wont be known when evaluating modules.  Isn't that a little confusing?

**Comment by mn416** [comment]
The `IfThenElse` instance is a good step forward.  One day we might take the plunge and support conditionals returning `Bits a => a`.

**Comment by gameboo** [comment]
> Looks good. The `testPlusArgs` instance for `Module` is a bit unexpected since simulator arguments wont be known when evaluating modules. Isn't that a little confusing?

The way I see it, simulator arguments are constant from the perspective of the design, so `testPlusArg` is like a `makeConstWire` or something similar. In the example I have it in an `Action` position but actually in my local changes to Pebbles'pipeline I have it all the way at the top in a Module context where I test `+DEBUG` and bind this to a value available to all stages of the pipeline so I can later go
```hs
when isDebug do displaLooks good. The testPlusArgs instance for Module is a bit unexpected since simulator arguments wont be known when evaluating modules. Isn't that a little confusing?y "your thing is broken stop trying to fix it"
```
... So I quite like the `Module` instance

> The IfThenElse instance is a good step forward. One day we might take the plunge and support conditionals returning Bits a => a.

Yes, it is quite silly of me to have done a `Bit` instance rather than `Bits` straight up actually... Should we drop that one then and do the proper one?

**Comment by mn416** [comment]
Happy to take the current `Bit n` instance of `IfThenElse` and then have a further PR for the `Bits` version.  The `Bits` version requires overlapping instances, which makes me a bit more cautious, but I think we should implement it to see if there are any unpleasant side-effects.

Regarding the PlusArgs thing, you could just write:

```hs
makeCPUPipeline :: Config -> Module ()
makeCPUPipeline c = do
  -- ... stuff
  isDebug <- always (testPlusArgs "DEBUG")
  -- ... more stuff
  always do
    when isDebug do display "your thing is broken stop trying to fix it"
```

**Comment by gameboo** [comment]
> We've gone for a distinction between `Module` and `Action`, so I feel a bit uncomfortable about hiding that distinction.

That's fair enough. Also, just for the sake of thinking this through all the way, what leads you to kill the `Module` instance rather than the `Action` instance?

**Comment by gameboo** [comment]
Just removed the `Module` instance

**Pull request merged**
