### PR TITLE
Add .cabal file and stack support. Tests also work on OSX, now.

### PR DESCRIPTION
**Pull request by ret**
Thanks for sharing Blarney! I'm having fun learning it!

I'm sending this pull request to see if you're interested in including support for `stack` and `.cabal` for Blarney. Later on, we could also add Cabal3 support, but I've not gotten around to that.
I also included a small change to `Test/test.sh` to replace `head -n -1`, which isn't supported on OSX. I've replaced it with the equivalent `sed` command to make the tests work on Linux and OSX. 

Would you be open to adding these build and package management related files in master?

### CODE REVIEW

**Comment by mn416** [comment]
Hi @ret,

Sorry for the slow reply, I missed this PR somehow.

I'd like to merge in your change to use `sed` instead of `head -n -1` due to the problem you report when using OSX.  If you create a PR with only this modification, I'll gladly merge it.  Or I can do the change myself at some point if that's too much trouble.

Regarding the packaging work, we're still thinking about it, so we'll revisit that side of the PR at a later date.

**Comment by ret** [comment]
Thanks for taking a look. I’ll send a separte PR for the OSX/sed change shortly.

**Comment by ret** [comment]
- The OSX compatibility change is in [43](https://github.com/mn416/blarney/pull/43). 
- I'm closing this PR: I still like blarney to use use a package manager (cabal-new or stack) to avoid relying on a system-level GHC installation, and/or -X flags in scripts. However, it would probably have to be a full changeover; the if/then/else's I sprinkled in the scripts to accommodate all variants were super ugly and not something for the long-term!

**Comment by mn416** [comment]
Ok, but still very grateful to have this PR.  It will be helpful when we get around to proper packaging.

**Pull request closed without merging**
