### PR TITLE
Suggestion for a new FSM combinator in Recipe

### PR DESCRIPTION
**Pull request by dillonhuff**
I noticed your project a few days ago. I work on high level synthesis so the little imperative language you provide (Recipe) for writing FSMs was very interesting to me.

However from what I could tell the Recipe language does not include any way to write pipelined loops (correct me if I'm wrong and there is some way to do loop pipelining with the existing recipes).

To remedy this I added a simple new primtive to Recipe: ```Launch```, which takes in a go signal and and Recipe, starts the Recipe and then immediately (in 0 cycles) continues to the next action, ignoring the finished signal from the argument to the ```Launch``` call.

I've added a simple example of how this combinator can be used to create a pipelined loop for vector add to the examples. If you run the testbench you can see that the pipelined version starts a new iteration of the loop every cycle instead of every other cycle, because thanks to the ```Launch``` semantics the loop does not have to wait for the data processing operations in one iteration to finish before starting the next operation.

Let me know what you think or if I've misunderstood how you implement loop pipelining.

### CODE REVIEW

**Comment by mn416** [comment]
Hi @dillonhuff,

That's pretty cool.  You can do something similar with existing constructs, e.g. to copy data from one ram to another:

```
load ram1 0
While (i.val .<. 100) (
  Action do
    store ram2 (i.val) (ram1.out)
    load ram1 (i.val + 1)
    i <== i.val + 1
)
```

But this needs two calls to `load` and hence an address bus mux, which your version neatly avoids, e.g.

```
While (i.val .<. 100) (
  Seq [
    Launch $ Seq [
      load ram1 (i.val),
      store ram2 (i.val.old) (ram1.out)
    ],
    i <== i.val + 1
)
```

I like it :)

Let's see if @gameboo has any input.

**Comment by gameboo** [comment]
Hi @dillonhuff,

I think @mn416 example using 2 loads could probably be written such that there is no additional address bus mux generated (I am thinking using `i.val + 1` as the argument in each call when `i` is initialized appropriately), but I agree with him that the `Lauch` construct makes things neater. I think the example itself is quite useful, and I would probably change a few details in there:
- consistent use of `act` / `Do [...]` (I would probably replace all 1 element `Do`s with an `act`)
- replace the uses of `Par` of trivial actions with `Action do` blocks (here the 3 `parA`)
- There is an initialization for `vecCPipe` but not for `vecCNoPipe` which I am not sure I follow. And for that matter, we probably don't need any initialization.

@mn416 do tell if some of the things I go on about here are nonsense :D, and can you think of other things?
I also think it would be nice to have the example structured similarly to the other ones in the examples directory, that is, with a `Makefile` and an `xxxxxxx.out` that plugs in with the `Test/test.sh`.

Separately from that, @dillonhuff you may be interested in having a look at https://github.com/CTSRD-CHERI/Recipe.
In there, we have similar constructs to what is in blarney's Recipe. We also have a `rPipe` recipe constructor that can be used in a similar fashion to the `Launch` construct. We had talked about folding some features from there into blarney. In general, the approach taken with those Bluespec `Recipe`s is that latency doesn't have to be known (I use this, for example, to interact with a memory subsystem where I don't necessarily know how many cycles could happen between the actions at the start of a sequence making a request and at the end of the sequence when a response is received. Two communicating state machines that are not perfectly in sync require some sort of backpressure mechanism.). I was thinking of using the `Stream` / `Source` and `Sink` interfaces to capture backpressure signals, and have a kind of action that also has a condition signal (in the fashion of Bluespec's guarded actions), and explicitly deal with latency as opposed to have it necessary part of every action (as it currently is the case with Blarney's `Do` construct).

Hope this is useful.

**Comment by mn416** [comment]
I agree with @gameboo on the simplifications.  I think I prefer to avoid the new `act` combinator for this simple example.  I think either `Action do a` or `Do [a]` is fine.

Regarding naming, this feature is somewhat similar to backgrounding processes on the UNIX command line using `&`.  So how about `Background` instead of `Launch`?

**Comment by mn416** [comment]
Thanks @dillonhuff, I've merged this.  I'm already using this new combinator in a different project, so wanted to get it into master now.

I'll do some of the suggested tidy ups myself, but please feel free to do another pull request if there are things you want to tweak.

Many thanks for your contribution.  I've added you to the copyright list at the top of Recipe.hs.  Do let me know if this is not ok...

**Comment by dillonhuff** [comment]
Glad you merged it! Sorry I didn't reply sooner. I've had an unexpected deadline come up so I'm a bit swamped.

**Pull request merged**
